# MLOps/config/common/global_vars.yaml
# For shared variables like date ranges, common paths.

# Example Date Ranges for Data Ingestion and Backtesting
date_ranges:
  training_start_date: "2025-01-01"
  training_end_date: "2025-03-31"
  backtesting_start_date: "2024-01-01"
  backtesting_end_date: "2024-06-30"

# Common Paths (examples, adjust as needed)
paths:
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  model_registry_dir: "MLOps/model_registry/"
  results_dir: "MLOps/results/"
  log_dir: "logs/"

# Other common configurations
default_tickers: ["AAPL", "MSFT"]