name: FinAI
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Conda Packages
  - python=3.11
  - numpy=1.26.4
  - pandas=2.0.3
  - scikit-learn=1.5.0
  - matplotlib
  - ipython
  - huggingface_hub
  - torch
  - transformers=4.38.2
  - accelerate=0.28.0
  - peft=0.10.0
  - nltk=3.8.1
  - tqdm=4.66.1
  - requests=2.31.0
  - setuptools>=41.4.0
  - wheel>=0.33.6
  - aiohttp=3.8.5
  - tenacity=8.3.0
  - starlette=0.37.2
  - typing_extensions>=4.12.0,<5.0
  # Pip Packages
  - pip
  - pip:
    - pyautogen[retrievechat]>=0.2.19
    - finnhub-python
    - yfinance
    - mplfinance
    - backtrader
    - sec_api
    - pyPDF2
    - reportlab
    - praw
    - tushare
    - pandas_datareader
    - pdfkit==1.0.0
    - marker-pdf
    - langchain==0.1.20
    - ratelimit==2.2.1
    - unstructured==0.8.1
    - ollama
    - fix-busted-json
    - openai>=1.0.0